### ISSUE TITLE
Unable to generate class without @AuraEnabled

### ISSUE THREAD

**Issue by Ko-Sit** [rrosset91/json2apexvscode#1]
There's inconsistency in vscode input placeholders and js handler. Should be just Y/N, not F/y

![image](https://user-images.githubusercontent.com/14953755/116245356-8fc30d80-a771-11eb-88bd-0ef7b2bd7b01.png)

p.s. marketplace is referencing incorrect branch (main)

**Comment by rrosset91** [comment]
thanks for reporting!

**Comment by rrosset91** [comment]
All corrected. Again, thanks and feel free to report more issues!
